FROM node:16-slim as builder
# Create app directory
WORKDIR /usr/src/app
COPY *.json ./
COPY ./src ./src
RUN npm install && npm run build

#release 
FROM nginx:stable-alpine
ENV NODE_ENV=production
WORKDIR /usr/src/app
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html/
COPY default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
