version: "3.3"

services:
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-014-12/pysy/pysy-frontend:$VERSION
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - pysy_networks

  backend:
    image: gitlab.praktikum-services.ru:5050/std-014-12/pysy/pysy-backend:$VERSION
    container_name: backend
    hostname: backend
    environment:
      - DEFAULT_HOST=backend
    networks:
      - pysy_networks
    healthcheck:
      test:  curl --fail -s http://localhost:8081/health/
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6


networks:
  pysy_networks:
    driver: bridge
